name: Build and Deploy Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Build and deploy
      run: |
        cd functions
        npm ci
        npm run deploy
      env:
        CI: true
