name: Build and Deploy Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Build
      working-directory: ./functions
      run: |
        npm ci
        npm run build
        npm run deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        CI: true
